/*
 * CatagoryWindow.java
 *
 * Created on November 23, 2007, 1:02 PM
 */

package envirofish;

/**
 *
 * @author  Donald Johnson
 */

import java.io.*;
import java.util.ArrayList;

public class CatagoryWindow extends javax.swing.JFrame {
    
    /** Creates new form CatagoryWindow */
    public CatagoryWindow() {
        catagory = new ArrayList<EvfCatagory>();
        
        initComponents();
    }
    
    public ArrayList<EvfCatagory> getCatagories()
    {
        return catagory;
    }
    
    private void close()
    {
        setVisible(false);
    }
    
    private void add()
    {
        catagory.add(new EvfCatagory("New Catagory",0.0));
        catagoryTableModel.fireTableDataChanged();
    }
    
    private void load()
    {
        fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f) 
            {
                if ( f.getName().endsWith(".cat") || f.isDirectory() )
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            public String getDescription() {
                return "Enviro Fish Catagory Files";
            }
        }
        );
        
        int rval = fc.showOpenDialog(this);
        if (rval == fc.APPROVE_OPTION )
        {
            loadFile(fc.getSelectedFile());
        }
    }
    
    private void loadFile(File file)
    {
        try
        {
            BufferedReader reader = new BufferedReader( new FileReader(file) );
            catagoryTableModel.clear();
            
            String line = reader.readLine();
            while(line != null && line != "" )
            {
                String part[] = line.split(",");
                catagory.add(new EvfCatagory(part[0],Double.parseDouble(part[1])));
                line = reader.readLine();
            }
            catagoryTableModel.fireTableDataChanged();
                       
        }
        catch (IOException ex )
        {
            ex.printStackTrace();
        }
    }

    private void save()
    {
        fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
            public boolean accept(File f)
            {
                if ( f.getName().endsWith(".cat") || f.isDirectory() )
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            public String getDescription() {
                return "Enviro Fish Catagory Files";
            }
        }
        );

        int rval = fc.showSaveDialog(this);
        if (rval == fc.APPROVE_OPTION )
        {
            saveFile(fc.getSelectedFile());
        }
    }

    private void saveFile(File file)
    {
        try
        {
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));

            for( int i = 0; i < catagory.size(); ++i )
            {
                writer.write(catagory.get(i).getName());
                writer.write(",");
                writer.write(Double.toString(catagory.get(i).getAmount()));
                writer.newLine();
            }

            writer.flush();
            writer.close();
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        fc = new javax.swing.JFileChooser();
        jTopBorderPanel = new javax.swing.JPanel();
        jCenterPanel = new javax.swing.JPanel();
        jLeftBorderPanel = new javax.swing.JPanel();
        jContentPanel = new javax.swing.JPanel();
        jTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonPanel = new javax.swing.JPanel();
        jAddButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLoadButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSaveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCloseButton = new javax.swing.JButton();
        jRightBorderPanel = new javax.swing.JPanel();
        jBottomBorderPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("Catagories Window");
        jTopBorderPanel.setMaximumSize(new java.awt.Dimension(32767, 10));
        jTopBorderPanel.setMinimumSize(new java.awt.Dimension(0, 10));
        jTopBorderPanel.setPreferredSize(new java.awt.Dimension(100, 10));
        javax.swing.GroupLayout jTopBorderPanelLayout = new javax.swing.GroupLayout(jTopBorderPanel);
        jTopBorderPanel.setLayout(jTopBorderPanelLayout);
        jTopBorderPanelLayout.setHorizontalGroup(
            jTopBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jTopBorderPanelLayout.setVerticalGroup(
            jTopBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        getContentPane().add(jTopBorderPanel);

        jCenterPanel.setLayout(new javax.swing.BoxLayout(jCenterPanel, javax.swing.BoxLayout.X_AXIS));

        jLeftBorderPanel.setMaximumSize(new java.awt.Dimension(10, 32767));
        jLeftBorderPanel.setMinimumSize(new java.awt.Dimension(10, 0));
        jLeftBorderPanel.setPreferredSize(new java.awt.Dimension(10, 100));
        javax.swing.GroupLayout jLeftBorderPanelLayout = new javax.swing.GroupLayout(jLeftBorderPanel);
        jLeftBorderPanel.setLayout(jLeftBorderPanelLayout);
        jLeftBorderPanelLayout.setHorizontalGroup(
            jLeftBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jLeftBorderPanelLayout.setVerticalGroup(
            jLeftBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jCenterPanel.add(jLeftBorderPanel);

        jContentPanel.setLayout(new javax.swing.BoxLayout(jContentPanel, javax.swing.BoxLayout.Y_AXIS));

        jTablePanel.setLayout(new javax.swing.BoxLayout(jTablePanel, javax.swing.BoxLayout.X_AXIS));

        catagoryTableModel = new EvfCatagoryTabelModel(catagory);
        jTable1.setModel(catagoryTableModel);
        jScrollPane1.setViewportView(jTable1);

        jTablePanel.add(jScrollPane1);

        jContentPanel.add(jTablePanel);

        jButtonPanel.setLayout(new javax.swing.BoxLayout(jButtonPanel, javax.swing.BoxLayout.X_AXIS));

        jButtonPanel.setMaximumSize(new java.awt.Dimension(32767, 30));
        jButtonPanel.setMinimumSize(new java.awt.Dimension(0, 30));
        jButtonPanel.setPreferredSize(new java.awt.Dimension(100, 30));
        jAddButton.setText("Add Cattgory");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jButtonPanel.add(jAddButton);

        jPanel1.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 100));
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jButtonPanel.add(jPanel1);

        jLoadButton.setText("Load Catagories");
        jLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadButtonActionPerformed(evt);
            }
        });

        jButtonPanel.add(jLoadButton);

        jPanel5.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 100));
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jButtonPanel.add(jPanel5);

        jSaveButton.setText("Save Catagories");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jButtonPanel.add(jSaveButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jButtonPanel.add(jPanel2);

        jCloseButton.setText("Close");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });

        jButtonPanel.add(jCloseButton);

        jContentPanel.add(jButtonPanel);

        jCenterPanel.add(jContentPanel);

        jRightBorderPanel.setMaximumSize(new java.awt.Dimension(10, 32767));
        jRightBorderPanel.setMinimumSize(new java.awt.Dimension(10, 0));
        jRightBorderPanel.setPreferredSize(new java.awt.Dimension(10, 100));
        javax.swing.GroupLayout jRightBorderPanelLayout = new javax.swing.GroupLayout(jRightBorderPanel);
        jRightBorderPanel.setLayout(jRightBorderPanelLayout);
        jRightBorderPanelLayout.setHorizontalGroup(
            jRightBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jRightBorderPanelLayout.setVerticalGroup(
            jRightBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jCenterPanel.add(jRightBorderPanel);

        getContentPane().add(jCenterPanel);

        jBottomBorderPanel.setMaximumSize(new java.awt.Dimension(32767, 10));
        jBottomBorderPanel.setMinimumSize(new java.awt.Dimension(0, 10));
        jBottomBorderPanel.setPreferredSize(new java.awt.Dimension(100, 10));
        javax.swing.GroupLayout jBottomBorderPanelLayout = new javax.swing.GroupLayout(jBottomBorderPanel);
        jBottomBorderPanel.setLayout(jBottomBorderPanelLayout);
        jBottomBorderPanelLayout.setHorizontalGroup(
            jBottomBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jBottomBorderPanelLayout.setVerticalGroup(
            jBottomBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        getContentPane().add(jBottomBorderPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        save();
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadButtonActionPerformed
        load();
    }//GEN-LAST:event_jLoadButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        add();
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
        close();
    }//GEN-LAST:event_jCloseButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    private ArrayList<EvfCatagory> catagory;
    private EvfCatagoryTabelModel catagoryTableModel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jAddButton;
    private javax.swing.JPanel jBottomBorderPanel;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JPanel jCenterPanel;
    private javax.swing.JButton jCloseButton;
    private javax.swing.JPanel jContentPanel;
    private javax.swing.JPanel jLeftBorderPanel;
    private javax.swing.JButton jLoadButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jRightBorderPanel;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jTablePanel;
    private javax.swing.JPanel jTopBorderPanel;
    // End of variables declaration//GEN-END:variables
    
}
